conn_lc:and conn:and conn_POS:CC with_prev_full:first_and xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:later conn:later conn_POS:RB with_prev_full:was_later xxx£
conn_lc:nonetheless conn:nonetheless conn_POS:RB xxx£
conn_lc:nonetheless conn:nonetheless conn_POS:RB with_prev_full:nonetheless_nonetheless xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:cramped_and xxx£
